### ISSUE TITLE
Feature request: Open image in a new tab

### ISSUE THREAD

**Issue by juanbretti** [NomarCub/obsidian-copy-url-in-preview#26]
Hello,
First, great plugin. Extremely useful.

Just a quick "Feature request".
Include an option to **open image in a new tab**.

I use the theme [Minimal](https://github.com/kepano/obsidian-minimal), and when I click on an image, this will temporary, overlay in full screen.
So, I cannot keep the image as full screen.

Workaround:
- Click on the image
- Ctrl+Click on the image name
- The images open in a new tab

Thank you for your consideration.

**Comment by NomarCub** [comment]
Hi!
I like the feature idea well enough and I think it's feasible. I looked around in the Obsidian API and I'm not clear on how to do this. I don't think I'll do this anytime soon due to time constraints, sorry. If you know other plugins that use the open in new window mechanism comment them, they might help me to explore the problem.
In the meanwhile, I recommend checking out other plugins that might have the functionality you need:
https://github.com/sissilab/obsidian-image-toolkit
https://obsidian.md/plugins?search=image

**Comment by waterproofsodium** [comment]
@juanbretti I created a pull request for duplicate request https://github.com/NomarCub/obsidian-copy-url-in-preview/issues/36
It opens the image in a new tab, with the path displayed as title. The middle mouse button can also be used to open in new tab.

**Comment by NomarCub** [comment]
I just released [1.7.0](https://github.com/NomarCub/obsidian-copy-url-in-preview/releases/tag/1.7.0), which includes this functionality. Let me know if there's anything wrong, either here or in a new issue.
